### ISSUE TITLE
按照demo的方法安装使用编辑器，出现“Method "init" has already been defined as a prop.”问题

### ISSUE THREAD

**Issue by QiuYX1994** [HaoChuan9421/vue-ueditor-wrap-demo#1]
![image](https://user-images.githubusercontent.com/37650775/46928932-85d3d600-d06f-11e8-9571-1cc66b01c9d4.png)
init方法使用和不使用都会出现这个问题

**Comment by haochuan9421** [comment]
你这个是重复定义的报错，比如你在data里定义了foo属性，在computed也定义foo属性，就会出现这个错误，英文也说的很清晰，你好好检查一下是不是你data,computed,props这三个里面有没有重复属性

**Comment by QiuYX1994** [comment]
我在项目里面，没有使用过“init”相关的参数和方法，这个是你写的编辑器里面使用的方法

**Comment by QiuYX1994** [comment]
![image](https://user-images.githubusercontent.com/37650775/46929253-1ced5d80-d071-11e8-8e02-5cbdc0670714.png)
![image](https://user-images.githubusercontent.com/37650775/46929195-e9aace80-d070-11e8-852f-773a0b7765ef.png)
![image](https://user-images.githubusercontent.com/37650775/46929225-fb8c7180-d070-11e8-9a1a-e0d77fc91a12.png)
![image](https://user-images.githubusercontent.com/37650775/46929233-047d4300-d071-11e8-9400-3a1589e9701a.png)
我在项目里只是使用了这个编辑器

**Comment by haochuan9421** [comment]
你这么说，我不好定位问题呀，init只是一个function类型的props，你不传的话默认一个空的函数，demo也没有报错呀，不明白你的哪里出问题了

**Comment by haochuan9421** [comment]
看你的代码好像没问题

**Comment by QiuYX1994** [comment]
编辑器有加载，也可以使用，只是不知道哪里出问题了，我全局去找init使用的地方，只有这个编辑器的文件里有用到

**Comment by haochuan9421** [comment]
如果你不用这个方法就直接删掉，实在看不出来问题出在哪里，如果你找到了可以反馈一下，避免其他人踩

**Comment by QiuYX1994** [comment]
你写的这个参数名字可以修改吗，如果可以我要怎么修改，模块里的文件好像是只读的

**Comment by QiuYX1994** [comment]
![image](https://user-images.githubusercontent.com/37650775/46929751-da795000-d073-11e8-8cc5-975d7dbfbe8d.png)
是这个文件里抱错的，这个可以修改名称吗，

**Comment by haochuan9421** [comment]
你要是想改直接把npm里面lib下的index.vue拷贝出来自己改就可以了，其实npm里面就是这么一个.vue文件

**Comment by QiuYX1994** [comment]
好，我试下可不可以解决

**Comment by haochuan9421** [comment]
你拷贝出来，把那两个地方删掉就可以

**Comment by haochuan9421** [comment]
不过很奇怪，为什么会报错，那个其实没啥问题的，demo跑起来都挺好的

**Comment by QiuYX1994** [comment]
修改命名就好了，应该是和我项目里的其他模块的js文件里的命名冲突了

**Comment by haochuan9421** [comment]
你修改的是什么名字？

**Comment by QiuYX1994** [comment]
修改这2个
![image](https://user-images.githubusercontent.com/37650775/46929891-d13cb300-d074-11e8-9060-edfd7cc959e6.png)

**Comment by QiuYX1994** [comment]
应该是我的项目里，其他模块有用到init这个参数，所以冲突了。我自己写的组件什么的，我一般不用init，应为怕冲突，一般我都会把init后面加上具体的功能名称
