### ISSUE TITLE
UEditor的上传图片、文件等是需要与后台配合的功能，我用红色圈起来的那个是后台的配置文件名称吗

### ISSUE THREAD

**Issue by QiuYX1994** [HaoChuan9421/vue-ueditor-wrap-demo#2]
![image](https://user-images.githubusercontent.com/37650775/47409811-83236000-d796-11e8-8357-56285c9a3701.png)

**Comment by haochuan9421** [comment]
整个serverURL的值是后端给你的完整地址，不清楚问一下后端

**Comment by QiuYX1994** [comment]
后端有给我一个地址，我放上去后出错了，提示：ueditor.all.min.js:9 请求后台配置项http错误，上传功能将不能正常使用！

**Comment by QiuYX1994** [comment]
后端要配置什么 文件，php的

**Comment by QiuYX1994** [comment]
![image](https://user-images.githubusercontent.com/37650775/47410160-7a7f5980-d797-11e8-855e-8d7885a1f60d.png)
提示这个

**Comment by QiuYX1994** [comment]
UEditor 这个是get请求。如果要修改成post请求，要怎么修改

**Comment by haochuan9421** [comment]
那就是后端的锅了，获取配置信息的不是普通的Ajax请求，而是jsonp的，所以肯定是get

**Comment by QiuYX1994** [comment]
这个可以设置直接的上传文件路径吗

**Comment by haochuan9421** [comment]
我觉得你可以先过一下官方文档http://fex.baidu.com/ueditor/
