### ISSUE TITLE
ueditor上传图片的功能是不是只能通过get请求

### ISSUE THREAD

**Issue by NicholasZhan** [HaoChuan9421/vue-ueditor-wrap-demo#3]
这边配置了serverUrl的接口  但是还是上传不了图片（我们后端是post请求）  下载demo又因为npm run dev报错  没有尝试

**Comment by haochuan9421** [comment]
UEditor会自动发送一个jsonp请求（相当于get），来判断后端的配置是否正确。在调试工具里，你会看到`serveUrl + ?action=config`的一个请求，这个请求会返回一些后端的配置。如果你的没有或者这个请求报错了，就说明后端配置错误。至于demo里npm run dev报错，你可能是npm包没安装好。

**Comment by NicholasZhan** [comment]
用了demo的也不行 应该是后端配置错误了,那后端配置要怎么配置  这边是已经允许跨域访问的了.
有PHP配置的教程链接吗？请求返回后端配置不行

**Comment by NicholasZhan** [comment]
万分感谢

**Comment by haochuan9421** [comment]
官方文档都有很详细的介绍 http://fex.baidu.com/ueditor/#server-php

**Comment by NicholasZhan** [comment]
好的，真的谢谢你了  我把问题反馈给后台

**Comment by NicholasZhan** [comment]
这边后端修改完以后单图上传可以触发了  但是每次上传都是loading状态  我的项目和你的demo都是这种情况  多图上传还是现实后端配置不正确...  如下截图 :
![image](https://user-images.githubusercontent.com/17342648/48120588-8269ee00-e2ad-11e8-9671-485351901a5a.png)
![image](https://user-images.githubusercontent.com/17342648/48120593-85fd7500-e2ad-11e8-9419-969d2cb949b1.png)
![image](https://user-images.githubusercontent.com/17342648/48120654-b34a2300-e2ad-11e8-842f-bd7867481c7e.png)
可以帮忙看看问题所在吗  谢谢啦

**Comment by haochuan9421** [comment]
单图上传跨域百度编辑器不支持，多图的话如果后端配置正确应该是可以的

**Comment by haochuan9421** [comment]
单图上传有一种取巧的方式，以供参考
![image](https://user-images.githubusercontent.com/5093611/48120805-23f13f80-e2ae-11e8-83cc-9c7176eb6241.png)

**Comment by NicholasZhan** [comment]
多图的话 后端配置没有报错了 但还是无法上传 用的是你上次提供的百度ueditor php源码还有配置
![image](https://user-images.githubusercontent.com/17342648/48122968-c95ae200-e2b3-11e8-8534-30e1dfe71645.png)

**Comment by haochuan9421** [comment]
后端提供的serveUrl如果没问题那个地方是可以选择图片的

**Comment by NicholasZhan** [comment]
http://47.106.97.169:8080/home/shopApi/ueditorConfig 能否配置一下 看看有什么问题... 后端的配置是否要和你demo提供的后端配置一致才行

**Comment by haochuan9421** [comment]
这是你们的
![image](https://user-images.githubusercontent.com/5093611/48124097-7f273000-e2b6-11e8-8d4b-821be05ad16f.png)
这是我们公司的
![image](https://user-images.githubusercontent.com/5093611/48124180-a5e56680-e2b6-11e8-92cb-2bb6e074d094.png)
你觉得你们后端配的有没有问题？

**Comment by haochuan9421** [comment]
我Demo只是前端，没有后端配置

**Comment by haochuan9421** [comment]
我晚上回去搭一个服务算了

**Comment by haochuan9421** [comment]
@NicholasZhan 我搭了一个上传接口，并更新了[Demo](https://haochuan9421.github.io/vue-ueditor-wrap-demo/)，serverUrl是 `http://35.201.165.105:8000/controller.php`，我只是在官方提供的PHP代码上按文档稍作了修改：
1. 设置允许跨域
![image](https://user-images.githubusercontent.com/5093611/48135028-b6a5d480-e2d6-11e8-968a-1cc21b6c627f.png)
2. 修改各种 xxxUrlPrefix 和 xxxPathFormat ,使得可以返回正确的文件存储路径。具体参数的作用截图里也有注释
![image](https://user-images.githubusercontent.com/5093611/48135354-ae9a6480-e2d7-11e8-8afb-70877a320e32.png)
然后把他们放到我的服务器上。
这些对后端来说是非常简单的事情，供你参考

**Comment by NicholasZhan** [comment]
OK了 我把配置截图给后端  他那边配好以后我可以正常上传了  谢谢作者 这边我给demo还有vue-editor库都已经star了  用了插件以后方便很多

**Comment by NicholasZhan** [comment]
这边把issue关闭了啊

**Comment by haochuan9421** [comment]
好的，能解决就好

**Comment by ghost** [comment]
**为什么我的就一直不行呢 ？？？**
![image](https://user-images.githubusercontent.com/29418930/91627944-d3505680-e9ed-11ea-8af4-6815956b90d9.png)

**Comment by ghost** [comment]
米有人理我 @ @HaoChuan9421 @NicholasZhan
