### ISSUE TITLE
加载ueditor.config.js失败,请检查您的配置地址UEDITOR_HOME_URL填写是否正确!

### ISSUE THREAD

**Issue by tongfei-github** [HaoChuan9421/vue-ueditor-wrap-demo#5]
![image](https://user-images.githubusercontent.com/31687243/62115362-e5435f80-b2ea-11e9-9a36-a0706b17330d.png)
请问 这个怎么解决

**Comment by zzhenxiang** [comment]
确认解压包的路径是否正确  UEDITOR_HOME_URL: '/static/UEditor/'

**Comment by Christoooooo** [comment]
vue cli 3.0 路径怎么配置

**Comment by 18673227300** [comment]
请问解决了吗
